### PR TITLE
feat: allow appVersion to be specified

### PR DESCRIPTION
**Pull request by silverjam**
Allows the `--app-version` switch to be passed to the `helm package` command.

### CODE REVIEW

**Comment by silverjam** [comment]
Hello @sergeyshaykhullin -- is this functionality that y'all might want?

**Comment by silverjam** [comment]
Thanks @sergeyshaykhullin !

**Comment by bluecamel** [comment]
@silverjam Could you please tag a release with this change?  Thanks!

Edit: sorry, tagged the wrong person.  @sergeyshaykhullin

**Comment by sergeyshaykhullin** [comment]
@sergeyshaykhullin Done

**Pull request merged**
